HomeWork22/Models/ErrorViewModel.cs
using System;

namespace HomeWork22.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HomeWork22/Models/Record.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HomeWork22.Models
{
    public class Record
    {
        public int ID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Phone { get; set; }
        public string Adress { get; set; }
        public string Info { get; set; }
    }
}

HomeWork22/Controllers/AccountController.cs
using HomeWork22.AuthApp;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HomeWork22.Controllers
{
    public class AccountController : Controller
    {
        private readonly UserManager<User> _userManager;

        private readonly SignInManager<User> _signInManager;

        public AccountController(UserManager<User> userManager, SignInManager<User> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }

        [HttpGet]
        public IActionResult Login(string returnUrl)
        {
            return View(new UserLogin()
            {
                returnUrl = returnUrl
            });
        }

        [HttpPost, ValidateAntiForgeryToken]
        //[Authorize]
        public async Task<IActionResult> Login(UserLogin model)
        {
            if (ModelState.IsValid)
            {
                var LoginResult = await _signInManager.PasswordSignInAsync(model.UserName,
                    model.Password, false, lockoutOnFailure: false);

                if (LoginResult.Succeeded)
                {
                    if (Url.IsLocalUrl(model.returnUrl))
                    {
                        return Redirect(model.returnUrl);
                    }
                    return RedirectToAction("RecordBook", "Record");
                }
            }

            ModelState.AddModelError("", "Пользователь не найден");

            return View(model);
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View(new UserRegistration());
        }

        [HttpPost]
        public async Task<IActionResult> Register(UserRegistration model)
        {
            if (ModelState.IsValid)
            {
                var user = new User() { UserName = model.UserName };
                var createResult = await _userManager.CreateAsync(user, model.Password);

                if (createResult.Succeeded)
                {
                    await _signInManager.SignInAsync(user, false);
                    return RedirectToAction("RecordBook", "Record");
                }
                else
                {
                    foreach (var item in createResult.Errors)
                    {
                        ModelState.AddModelError("", item.Description);
                    }
                }
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return View();
        }
    }
}

HomeWork22/Controllers/RecordController.cs
using HomeWork22.Interface;
using HomeWork22.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HomeWork22.Controllers
{
    public class RecordController : Controller
    {
        private readonly IRecord Record;

        public RecordController(IRecord record)
        {
            this.Record = record;
        }

        public IActionResult Index()
        {
            return View(Record.GetData());
        }

        [HttpGet]
        [Authorize]
        public IActionResult RecordBook()
        {
            return View(Record.GetData());
        }

        [HttpGet]
        [Authorize]
        public IActionResult Add()
        {
            return View();
        }

        [Authorize]
        [HttpGet]
        public IActionResult RecordPage()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public IActionResult GetDataFromViewFields(string lastName, string firstName, string middleName, string phone, string adress, string info)
        {
            var record = new Record()
            {
                LastName = lastName,
                FirstName = firstName,
                MiddleName = middleName,
                Phone = phone,
                Info = info
            };
            Record.Add(record);
            return Redirect("~/");
        }
    }
}

HomeWork22/ViewComponent/LogoutViewViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HomeWork22.ViewComponents
{
    public class LogoutViewViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

HomeWork22/Views/Record/Add.cshtml
@model HomeWork22.Controllers.RecordController
@{
}

<h1 class="text-black-50">Добавьте запись</h1>
<div class="card m-3">
    <form action="~/Record/GetDataFromViewFields" method="post">
        <table>
            <tr>
                <td>Фамилия</td>
                <td><input type="text" name="LastName" /></td>
            </tr>
            <tr>
                <td>Имя</td>
                <td><input type="text" name="FirstName" /></td>
            </tr>
            <tr>
                <td>Отчество</td>
                <td><input type="text" name="MiddleName" /></td>
            </tr>
            <tr>
                <td>Телефон</td>
                <td><input type="text" name="Phone" /></td>
            </tr>
            <tr>
                <td>Адрес</td>
                <td><input type="text" name="Adress" /></td>
            </tr>
            <tr>
                <td>Информация</td>
                <td><input type="text" name="Info" /></td>
            </tr>
        </table><br />
        <input type="submit" value="Добавить" />
    </form>
</div>

HomeWork22/Views/Record/Index.cshtml
@using HomeWork22.Models

@{
}
<h1 class="text-black-50">Записная книжка</h1>
<div class="row">
    @foreach (Record item in Model)
    {
        <div class="col-sm-3">
            <div class="card-deck">
                <div class="card m-3">
                    <div class="text-center">
                        <h3>@item.LastName</h3>
                    </div>
                    <div>
                        <img class="card-img-top" photo src="~/photo/depositphotos_51402215-stock-illustration-male-avatar-profile-picture-use.jpg" />
                    </div>
                    <h4>@item.FirstName</h4>
                    <h4>@item.MiddleName</h4><br />                    
                </div>
            </div>
        </div>
    }

HomeWork22/Views/Record/RecordBook.cshtml
@using HomeWork22.Models

@{
}
<h1 class="text-black-50">Записная книжка</h1>
<div class="row">
    @foreach (Record item in Model)
    {
        <div class="col-sm-3">
            <div class="card-deck">
                <div class="card m-3">
                    <div class="text-center">
                        <h3>@item.LastName</h3>
                    </div>
                    <div>
                        <img class="card-img-top" photo src="~/photo/depositphotos_51402215-stock-illustration-male-avatar-profile-picture-use.jpg" />
                    </div>
                    <h4>
                        <a href="/Record/RecordPage" class="btn btn-info">ID: @item.ID</a>
                    </h4>
                    <h4>@item.FirstName</h4>
                    <h4>@item.MiddleName</h4><br />                   
                </div>
            </div>
        </div>
    }
</div>
<a asp-controller="Record" asp-action="Add">Добавить запись</a>

HomeWork22/Views/Record/RecordPage.cshtml
<h1>Информация</h1>

HomeWork22/Views/Shared/Components/LogoutView/Default.cshtml
@if(User.Identity.IsAuthenticated)
{
    <div>
        <a class="navbar" href="~/">В начало</a>
        <a class="navbar" href="/Record/Add">Добавить запись</a>
        <form method="post" asp-controller="Account" asp-action="Logout" id="logout">
            <a class="navbar" href="/Account/Login" onclick="document.getElementById('logout').submit()">Выйти</a>
        </form>
    </div>
}
else
{
    <div>
        <a class="navbar" href="/Account/Login">Войти</a>
        <a class="navbar" href="/Account/Register">Регистрация</a>
    </div>
}

HomeWork22/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HomeWork21</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <nav class="navbar">
        <div>@await Component.InvokeAsync("LogoutView")</div>
    </nav>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>